
Browser("Certificate Error: Navigation").Page("Certificate Error: Navigation").Link("Click here to close this").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Certificate Error: Navigation").Link("Click here to close this")_;_script infofile_;_ZIP::ssf25.xml_;_
Browser("Certificate Error: Navigation").Dialog("Windows Internet Explorer").WinButton("No").Click @@ hightlight id_;_1442602_;_script infofile_;_ZIP::ssf26.xml_;_
Browser("Certificate Error: Navigation").Page("Certificate Error: Navigation").Link("Click here to close this").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Certificate Error: Navigation").Link("Click here to close this")_;_script infofile_;_ZIP::ssf27.xml_;_
Browser("Certificate Error: Navigation").Dialog("Windows Internet Explorer").WinButton("No").Click @@ hightlight id_;_2425168_;_script infofile_;_ZIP::ssf28.xml_;_
Browser("Certificate Error: Navigation").WinObject("Notification bar").WinButton("Close").Click @@ hightlight id_;_1993263904_;_script infofile_;_ZIP::ssf29.xml_;_
Browser("Certificate Error: Navigation").Page("Certificate Error: Navigation").Link("Continue to this website").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Certificate Error: Navigation").Link("Continue to this website")_;_script infofile_;_ZIP::ssf30.xml_;_
Browser("Certificate Error: Navigation").Page("Bienvenidos a la Banca").Link("Cuentas y Tarjetas").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Bienvenidos a la Banca").Link("Cuentas y Tarjetas")_;_script infofile_;_ZIP::ssf31.xml_;_
Browser("Certificate Error: Navigation").Page("Bienvenidos a la Banca").Link("Cuentas con chequera").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Bienvenidos a la Banca").Link("Cuentas con chequera")_;_script infofile_;_ZIP::ssf32.xml_;_
Browser("Certificate Error: Navigation").Page("Cuentas con Chequera |").WebElement("Documentos").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Cuentas con Chequera |").WebElement("Documentos")_;_script infofile_;_ZIP::ssf33.xml_;_
Browser("Certificate Error: Navigation").Page("Cuentas con Chequera |").WebElement("NóminaNómina BancomerCambia").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Cuentas con Chequera |").WebElement("NóminaNómina BancomerCambia")_;_script infofile_;_ZIP::ssf34.xml_;_
Browser("Certificate Error: Navigation").Page("Cuentas con Chequera |").Link("Características y beneficios").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Cuentas con Chequera |").Link("Características y beneficios")_;_script infofile_;_ZIP::ssf35.xml_;_
Browser("Certificate Error: Navigation").Page("Nómina Bancomer").Link("Ahorro e Inversión").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Nómina Bancomer").Link("Ahorro e Inversión")_;_script infofile_;_ZIP::ssf36.xml_;_
Browser("Certificate Error: Navigation").Page("Nómina Bancomer").Link("Fondos de Inversión").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Nómina Bancomer").Link("Fondos de Inversión")_;_script infofile_;_ZIP::ssf37.xml_;_
Browser("Certificate Error: Navigation").Page("Fondos de inversión |").Link("Préstamo Personal").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Fondos de inversión |").Link("Préstamo Personal")_;_script infofile_;_ZIP::ssf38.xml_;_
Browser("Certificate Error: Navigation").Page("Préstamos personales |").Link("Seguros").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Préstamos personales |").Link("Seguros")_;_script infofile_;_ZIP::ssf39.xml_;_
Browser("Certificate Error: Navigation").Page("Préstamos personales |").Link("Conductor responsable").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Préstamos personales |").Link("Conductor responsable")_;_script infofile_;_ZIP::ssf40.xml_;_
Browser("Certificate Error: Navigation").Page("Seguro conductor responsable").WebElement("Características").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Seguro conductor responsable").WebElement("Características")_;_script infofile_;_ZIP::ssf41.xml_;_
Browser("Certificate Error: Navigation").Page("Seguro conductor responsable").WebElement("Características").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Seguro conductor responsable").WebElement("Características")_;_script infofile_;_ZIP::ssf42.xml_;_
Browser("Certificate Error: Navigation").Page("Seguro conductor responsable").WebElement("Servicios DigitalesInternetBan").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Seguro conductor responsable").WebElement("Servicios DigitalesInternetBan")_;_script infofile_;_ZIP::ssf43.xml_;_
Browser("Certificate Error: Navigation").Page("Seguro conductor responsable").Link("Línea Bancomer").Click @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Seguro conductor responsable").Link("Línea Bancomer")_;_script infofile_;_ZIP::ssf44.xml_;_
Browser("Certificate Error: Navigation").Page("Línea Bancomer Personas").Sync @@ hightlight id_;_Browser("Certificate Error: Navigation").Page("Línea Bancomer Personas")_;_script infofile_;_ZIP::ssf45.xml_;_
Browser("Certificate Error: Navigation").CloseAllTabs
